[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.24"
optimizer = true
optimizer-runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
     "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
     "@ethereum-attestation-service/eas-contracts=lib/eas-contracts/contracts"
]